### ISSUE TITLE
Create and implement theme system

### ISSUE THREAD

**Issue by JohanPeraldi** [JohanPeraldi/poker-range-manager#11]
# Theme System Implementation

## Tasks
- [ ] Set up theme configuration in Tailwind
- [ ] Create predefined color palettes:
  - Warm beige
  - Cool gray
  - Soft green
  - Subtle blue
- [ ] Implement theme switching mechanism
- [ ] Create theme selector component
- [ ] Add theme persistence in localStorage

## Color Palettes
```javascript
// Example theme structure
const themes = {
  warmBeige: {
    base: '#f1ece0',
    highlight: '#f8f4ea',
    hover: '#e5dcc8',
    border: 'gray-300'
  },
  softGreen: {
    base: '#eef2ee',
    highlight: '#f5f7f5',
    hover: '#dce3dc',
    border: 'gray-300'
  },
  // ... other themes
}
```

## Technical Details
- Update Tailwind configuration
- Create theme context for state management
- Add theme selector UI
- Implement local storage for theme persistence
- Add smooth transitions between themes

## Definition of Done
- Multiple themes are available
- Theme switching works smoothly
- Theme persists after page reload
- Theme selector is intuitive
- Transitions are smooth

## Notes
- Keep color contrast accessibility in mind
- Ensure consistent spacing across themes
- Consider dark mode support for future
