### ISSUE TITLE
Create position selector component

### ISSUE THREAD

**Issue by JohanPeraldi** [JohanPeraldi/poker-range-manager#12]
# Position Selector Implementation

## Tasks
- [x] Create PositionSelector component
- [x] Implement position state management
- [x] Style position buttons
- [x] Link positions to grid state
- [x] Add visual feedback for selected position

## Positions to Include
- BTN (Button)
- CO (Cut-off)
- HJ (Hijack)
- LJ (Lojack)
- SB (Small Blind)
- BB (Big Blind)

## Technical Details
```javascript
// Example position data structure
const positions = [
  { id: 'BTN', name: 'Button', shortName: 'BTN' },
  { id: 'CO', name: 'Cut-off', shortName: 'CO' },
  { id: 'HJ', name: 'Hijack', shortName: 'HJ' },
  { id: 'LJ', name: 'Lojack', shortName: 'LJ' },
  { id: 'SB', name: 'Small Blind', shortName: 'SB' },
  { id: 'BB', name: 'Big Blind', shortName: 'BB' }
];
```

## Component Features
- Clear position indicators
- Active state for selected position
- Responsive design
- Tooltips with full position names
- Keyboard navigation support

## Definition of Done
- All positions are displayed correctly
- Position selection works properly
- Selected position is clearly indicated
- Component is responsive
- Position state affects grid display
- Keyboard navigation works

## Notes
- Consider mobile-friendly layout
- Add hover states for better UX
- Consider adding position descriptions for beginners
- Ensure proper spacing between buttons
