### ISSUE TITLE
Configure Tailwind CSS styles and theme

### ISSUE THREAD

**Issue by JohanPeraldi** [JohanPeraldi/poker-range-manager#2]
# Tailwind CSS Configuration and Theme Setup

## Tasks
- [x] Review and customize Tailwind config
- [x] Set up custom color scheme
- [x] Configure any needed plugins
- [x] Set up base styles in globals.css
- [x] Create reusable utility classes

## Configuration Files
1. tailwind.config.js should include:
```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx}",
    "./src/app/**/*.{js,jsx}",
    "./src/components/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        'raise': '#ff0000',
        'call': '#add8e6',
        'fold': '#808080',
      },
    },
  },
  plugins: [],
}
```
2. src/app/globals.css:
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

/* Custom base styles */
@layer base {
  body {
    @apply bg-white text-gray-900;
  }
}

/* Custom component styles */
@layer components {
  .grid-cell {
    @apply aspect-square border border-gray-200 flex items-center justify-center cursor-pointer hover:opacity-90;
  }
}
```
## Definition of Done
- Tailwind configuration is optimized
- Custom colors are defined
- Base styles are set up
- Utility classes are tested
- Build process runs without errors

## Notes
- Keep color scheme consistent
- Consider dark mode support
- Ensure responsive design utilities
