### ISSUE TITLE
Deploy MVP

### ISSUE THREAD

**Issue by JohanPeraldi** [JohanPeraldi/poker-range-manager#22]
# Deploy MVP

## Description
Deploy the MVP version for online testing and user feedback.

## Tasks

- [x] Choose deployment platform (e.g., Vercel, Netlify)
- [x] Configure build settings
- [x] Set up environment variables if needed
- [x] Configure domain settings
- [x] Perform deployment tests
- [x] Verify all features work in production
- [x] Set up monitoring/analytics
- [x] Document deployment process
