### ISSUE TITLE
Set up Next.js app directory structure and initial components

### ISSUE THREAD

**Issue by JohanPeraldi** [JohanPeraldi/poker-range-manager#3]
# Project Structure Setup

## Tasks
- [x] Set up app directory structure
- [x] Create base layout component
- [x] Create initial page component
- [x] Set up component directories
- [x] Create context directory
- [x] Set up constants and utils

## Directory Structure
```
src/
├── app/
│   ├── layout.jsx             # Root layout with providers
│   ├── page.jsx               # Home page component
│   └── globals.css            # Global styles
├── components/
│   ├── Grid/
│   │   ├── Grid.jsx           # Main grid component
│   │   ├── GridCell.jsx       # Individual cell component
│   │   └── gridUtils.js       # Grid helper functions
│   ├── PositionSelector/
│   │   └── PositionSelector.jsx
│   ├── ColorPicker/
│   │   └── ColorPicker.jsx
│   └── RangeControls/
│       └── RangeControls.jsx
├── contexts/
│   └── RangeContext.jsx       # Global state management
├── constants/
│   ├── positions.js           # Table position constants
│   ├── actions.js             # Action type constants
│   └── colors.js              # Default colors
└── utils/
├── storage.js                 # Local storage functions
└── handUtils.js               # Hand calculation utilities
```

## Initial Component Templates
1. app/layout.jsx:
```jsx
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* RangeContext Provider will go here */}
        {children}
      </body>
    </html>
  );
}
```
2. app/page.jsx:
```jsx
'use client'

export default function Home() {
  return (
    <main className="container mx-auto px-4">
      {/* Main app components will go here */}
    </main>
  );
}
```

## Definition of Done
- All directories are created
- Basic component files are created
- Layout component is set up
- Page component is working
- File structure matches plan
- Components can be imported

## Notes
- Use 'use client' directive where needed
- Keep components organized by feature
- Set up proper exports
- Use consistent naming
- Consider component reusability
