### ISSUE TITLE
Create hand range grid layout component

### ISSUE THREAD

**Issue by JohanPeraldi** [JohanPeraldi/poker-range-manager#4]
# Hand Range Grid Layout Implementation

## Tasks
- [x] Create basic Grid component structure
- [x] Define grid layout (13x13 matrix)
- [x] Implement basic poker hand display logic
- [x] Style grid cells with Tailwind CSS
- [x] Ensure responsive design

## Component Requirements
- Display all possible poker hand combinations
- Show suited hands above diagonal
- Show off-suit hands below diagonal
- Show pocket pairs on diagonal
- Grid should be responsive and maintain aspect ratio

## Implementation Details
```jsx
// Grid structure example:
const hands = [
  ['AA', 'AKs', 'AQs', ...],
  ['AKo', 'KK', 'KQs', ...],
  ['AQo', 'KQo', 'QQ', ...],
  // ...
];
```

## Styling Requirements
- Use Tailwind CSS grid classes
- Implement hover effects
- Ensure readable text contrast
- Make grid cells square
- Add borders between cells

## Definition of Done
- Grid displays all possible poker hands
- Layout is correct and responsive
- Basic styling is implemented
- Component renders without errors
- Hands are properly positioned in grid

## Notes
- Focus on structure first, interaction will be added later
- Ensure accessibility considerations
- Comment code for clarity
