### ISSUE TITLE
Implement interactive grid cell component

### ISSUE THREAD

**Issue by JohanPeraldi** [JohanPeraldi/poker-range-manager#5]
# Grid Cell Component Implementation

## Tasks
- [x] Create GridCell component
- [x] Implement click handling
- [x] Add color state management
- [x] Style different states (raise, call, fold)
- [x] Add hover effects

### Props
- hand: string (e.g., 'AA', 'AKs', 'T9o')
- action: string ('raise', 'call', 'fold', null)
- onClick: function
- isSelected: boolean
- colorScheme: object

### Visual States
- Default state (no action)
- Raise state (red)
- Call state (light blue)
- Fold state (grey)
- Hover state

## Sample Component Structure
```jsx
const GridCell = ({ hand, action, onClick, colorScheme }) => {
  const cellColor = action ? colorScheme[action] : 'transparent';
  
  return (
    <div 
      className="grid-cell" 
      style={{ backgroundColor: cellColor }}
      onClick={() => onClick(hand)}
    >
      {hand}
    </div>
  );
};
```

## Styling Requirements
- Square aspect ratio
- Centered text
- Clear color indicators
- Smooth transitions
- Hover feedback

## Definition of Done
- Cell renders correctly
- Click handling works
- Color states work
- Hover effects work
- Component is reusable

## Notes
- Keep component pure and focused
- Ensure good performance
- Make colors customizable
