### ISSUE TITLE
Create position selector component

### ISSUE THREAD

**Issue by JohanPeraldi** [JohanPeraldi/poker-range-manager#6]
# Position Selector Implementation

## Tasks
- [x] Create PositionSelector component
- [x] Define positions (BTN, CO, HJ, LJ, SB, BB)
- [x] Implement position selection logic
- [x] Style selector with Tailwind CSS
- [x] Add position highlights/active states

### Positions to Include
- BTN (Button)
- CO (Cut-off)
- HJ (Hijack)
- LJ (Lojack)
- SB (Small Blind)
- BB (Big Blind)

### Features
- Clear position indicators
- Active state for selected position
- Easy-to-click targets
- Optional position descriptions/tooltips

## Sample Structure
```jsx
const positions = [
  { id: 'BTN', name: 'Button', description: 'Last to act pre-flop' },
  { id: 'CO', name: 'Cut-off', description: 'Second to last to act' },
  // ... other positions
];

const PositionSelector = ({ selectedPosition, onPositionSelect }) => {
  return (
    <div className="position-selector">
      {positions.map(position => (
        <button
          key={position.id}
          onClick={() => onPositionSelect(position.id)}
          className={`position-button ${selectedPosition === position.id ? 'active' : ''}`}
        >
          {position.id}
        </button>
      ))}
    </div>
  );
};
```

## Styling Requirements
- Clear visual hierarchy
- Obvious active state
- Mobile-friendly touch targets
- Consistent spacing
- Proper alignment

## Definition of Done
- All positions are displayed
- Selection works correctly
- Active state is clear
- Component is responsive
- Styling matches design

## Notes
- Consider keyboard navigation
- Add hover states
- Consider adding position explanations for beginners
