### ISSUE TITLE
Set up RangeContext for state management in Next.js

### ISSUE THREAD

**Issue by JohanPeraldi** [JohanPeraldi/poker-range-manager#7]
# Range Context Implementation for Next.js

## Tasks
- [x] Create RangeContext with 'use client' directive
- [x] Implement RangeProvider component
- [x] Define initial state structure
- [x] Create state management actions
- [x] Add context to root layout

## Implementation Details

1. contexts/RangeContext.jsx:
```jsx
'use client'

import { createContext, useContext, useReducer } from 'react';

const initialState = {
  selectedPosition: 'BTN',
  ranges: {
    BTN: {},
    CO: {},
    HJ: {},
    LJ: {},
    SB: {},
    BB: {}
  },
  colors: {
    raise: '#ff0000',
    call: '#add8e6',
    fold: '#808080'
  }
};

const RangeContext = createContext();

export const RangeProvider = ({ children }) => {
  const [state, dispatch] = useReducer(rangeReducer, initialState);
  
  const value = {
    state,
    setSelectedPosition: (position) => {},
    updateHandAction: (hand, action) => {},
    // other actions
  };

  return (
    <RangeContext.Provider value={value}>
      {children}
    </RangeContext.Provider>
  );
};
```

2. Integration in app/layout.jsx:
```jsx
import { RangeProvider } from '@/contexts/RangeContext';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <RangeProvider>
          {children}
        </RangeProvider>
      </body>
    </html>
  );
}
```

## Required Actions
- setSelectedPosition
- updateHandAction
- updateRangeForPosition
- updateColors
- resetRange
- loadRange
- saveRange

## State Updates
```jsx
const rangeReducer = (state, action) => {
  switch (action.type) {
    case 'SET_POSITION':
      return {
        ...state,
        selectedPosition: action.payload
      };
    case 'UPDATE_HAND':
      return {
        ...state,
        ranges: {
          ...state.ranges,
          [state.selectedPosition]: {
            ...state.ranges[state.selectedPosition],
            [action.payload.hand]: action.payload.action
          }
        }
      };
    // other cases
  }
};
```

## Definition of Done
- Context and Provider are implemented
- 'use client' directive is properly used
- Provider is integrated in root layout
- All actions are defined and working
- State updates work correctly
- Components can access context
- State persistence works

## Notes
- Ensure client-side only execution
- Keep state updates immutable
- Consider using useCallback for action functions
- Add error boundary
- Document state shape
- Consider performance optimizations
