### ISSUE TITLE
Implement local storage functionality with Next.js

### ISSUE THREAD

**Issue by JohanPeraldi** [JohanPeraldi/poker-range-manager#8]
# Local Storage Implementation for Next.js

## Tasks
- [x] Create storage utility functions
- [x] Add 'use client' directive
- [x] Implement save range functionality
- [x] Implement load range functionality
- [x] Add error handling
- [x] Test storage operations

## Implementation Details

1. utils/storage.js:
```javascript
'use client'

const STORAGE_KEY = 'poker-range-manager';

// Check for window object to ensure client-side execution
const isClient = typeof window !== 'undefined';

export const saveToLocalStorage = (position, rangeData) => {
  if (!isClient) return;
  
  try {
    const existingData = localStorage.getItem(STORAGE_KEY);
    const allRanges = existingData ? JSON.parse(existingData) : {};
    allRanges[position] = rangeData;
    localStorage.setItem(STORAGE_KEY, JSON.stringify(allRanges));
    return true;
  } catch (error) {
    console.error('Error saving range:', error);
    return false;
  }
};

export const loadFromLocalStorage = (position) => {
  if (!isClient) return null;
  
  try {
    const data = localStorage.getItem(STORAGE_KEY);
    if (!data) return null;
    const allRanges = JSON.parse(data);
    return allRanges[position] || null;
  } catch (error) {
    console.error('Error loading range:', error);
    return null;
  }
};

export const clearStorage = (position = null) => {
  if (!isClient) return;
  
  try {
    if (position) {
      const data = localStorage.getItem(STORAGE_KEY);
      if (data) {
        const allRanges = JSON.parse(data);
        delete allRanges[position];
        localStorage.setItem(STORAGE_KEY, JSON.stringify(allRanges));
      }
    } else {
      localStorage.removeItem(STORAGE_KEY);
    }
    return true;
  } catch (error) {
    console.error('Error clearing storage:', error);
    return false;
  }
};
```

## Features
- Save ranges by position
- Load ranges by position
- Clear specific ranges
- Clear all ranges
- Export ranges to JSON
- Import ranges from JSON
- Client-side execution checks

## Error Handling
- Handle storage quota exceeded
- Handle invalid JSON
- Handle missing data
- Handle server-side rendering contexts
- Provide feedback for operations
- Data validation

## Usage in Components
```jsx
'use client'

import { saveToLocalStorage, loadFromLocalStorage } from '@/utils/storage';

// In a component:
const handleSave = () => {
  const success = saveToLocalStorage('BTN', rangeData);
  if (success) {
    // Show success message
  } else {
    // Show error message
  }
};
```

## Definition of Done
- All storage operations work on client side
- Server-side rendering is properly handled
- Error handling is implemented
- Import/Export works
- Storage operations are tested
- User feedback is implemented

## Notes
- Always check for client-side execution
- Add data validation
- Include version control for saved data
- Document storage format
- Consider backup strategies
- Test in different browsers
- Handle storage limitations
