### ISSUE TITLE
Create action and color picker component

### ISSUE THREAD

**Issue by JohanPeraldi** [JohanPeraldi/poker-range-manager#9]
# Action/Color Picker Implementation

## Tasks
- [ ] Create ColorPicker component
- [ ] Implement action selection buttons
- [ ] Add color customization interface
- [ ] Create color presets
- [ ] Implement color change handlers

### Actions
- Raise (default: red)
- Call (default: light blue)
- Fold (default: grey)

### Features
```jsx
const defaultColors = {
  raise: '#ff0000',
  call: '#add8e6',
  fold: '#808080'
};

const ColorPicker = ({ 
  selectedAction, 
  colors, 
  onActionSelect, 
  onColorChange 
}) => {
  return (
    <div className="color-picker">
      {/* Action buttons */}
      {/* Color input for selected action */}
      {/* Color presets */}
    </div>
  );
};
```

## UI Elements
- Action toggle buttons
- Color input for selected action
- Color preset buttons
- Reset to default button
- Current selection indicator

## Styling Requirements
- Clear action buttons
- Visual feedback on selection
- Accessible color inputs
- Mobile-friendly controls
- Proper spacing and alignment

## Interaction Flow
1. User selects an action (Raise/Call/Fold)
2. Current color is displayed
3. User can:
- Use color input to change color
- Select from presets
- Reset to default

## Definition of Done
- All actions can be selected
- Colors can be customized
- Presets work correctly
- UI is responsive
- Changes reflect in grid
- Default colors can be restored

## Notes
- Ensure color contrast for accessibility
- Save color preferences
- Consider colorblind users
- Add tooltips for clarity
- Keep UI simple and intuitive
